name: iosApp
options:
  bundleIdPrefix: be.sigmadelta
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: ""

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: be.sigmadelta.simplek
        PRODUCT_NAME: SimpleK Demo
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework"
          - "$(SRCROOT)/../composeApp/build/bin/iosArm64/debugFramework"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-framework"
          - "ComposeApp"
    postBuildScripts:
      - name: Copy Compose Resources
        script: |
          mkdir -p "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/compose-resources/composeResources/kankan.demo.composeapp.generated.resources"
          cp -R "${SRCROOT}/../composeApp/build/generated/compose/resourceGenerator/preparedResources/commonMain/composeResources/"* "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/compose-resources/composeResources/kankan.demo.composeapp.generated.resources/"
        basedOnDependencyAnalysis: false
    dependencies: []
